baseurl = "https://astro.wren.dev/"
metaDataFormat = "yaml"
title = "Nights of Wren"
theme = "arcsecond"
pluralizeListTitles =  false

[[menus.main]]
name = 'Gallery'
pageRef = '/gallery'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1
    languageCode = "en-US"
    languageName = "English"

[params]
  logo = "logo.svg"
  favicon = "icon.svg"
  front_page = "gallery"
  infinite_scroll = true
  search_hotkey = '/'
  star_charts_from = "pixinsight"
  custom_css = [ "css/shimmer.css" ]

[params.comments]
  system = "giscus"
  repo = "wrenby/wrenby.github.io"
  repo_id = "R_kgDOHxgI1g"
  category = "General"
  category_id = "DIC_kwDOHxgI1s4CVd-b"
  reactions_enabled = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
