baseurl = "https://astro.wren.dev/"
metaDataFormat = "yaml"
title = "Nights of Wren"
theme = "blist"
pluralizeListTitles =  false

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      #introTitle = "Hi! I'm Wren"
      subtitle = "Astrophotography by Wren Baxter"
      #introPhoto = "/picture.jpg"
      #logo = "/blist-logo.png"
    [[languages.en.menu.main]]
        name = "about"
        url = "about"
        weight = 1

    [[languages.en.menu.main]]
        name = "blog"
        url = "blog"
        weight = 2

    [[languages.en.menu.main]]
        name = "gallery"
        url = "gallery"
        weight = 3

    [[languages.en.menu.main]]
        name = "tags"
        url = "tags"
        weight = 4

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Powered by \u003ca href='https://gohugo.io'\u003eHugo\u003c/a\u003e · Copyright © 2022 Wren Baxter · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  accentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "gallery"

[imaging]
  anchor = "Center"

[params.homepage.social]
  title = "Find me here"
  #description = "or don't, i'm not your mom"
  rss = "/index.xml"
  #twitter = "https://twitter.com/"
  reddit = "https://reddit.com/wrenby_astro"
  instagram = "https://instagram.com/wrenby_astro"
  cloudynights = "https://www.cloudynights.com/user/398565-wrenby/"
  github = "https://github.com/wrenby"
  #keybase = "https://keybase.io/wrenby"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
